
# See the documentation for details:
#   -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/{{ cookiecutter.project_name }}"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/{{ cookiecutter.project_name }}"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/{{ cookiecutter.project_name }}"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/{{ cookiecutter.project_name }}/theme"
    schedule:
      interval: "daily"
