# Generated by Django 4.1.4 on 2022-12-11 01:00

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=timezone_field.fields.TimeZoneField(default="America/New_York"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email address"),
        ),
    ]
