default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude_types:
          - svg
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude_types:
          - svg
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude_types:
          - batch
      - id: fix-byte-order-marker

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.20.1
    hooks:
    - id: toml-sort
      args: [--in-place, --all]
      exclude: |
        (?x)(
          poetry.lock
        )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
        args: ["--tabwidth=2"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: ["-x", "-e", "SC1091"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: name-tests-test
        args: ["--django"]
        exclude: tests/(factories|fixtures)
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-ast
      - id: check-json
        # Exclude VSCode's settings.json since it's actually JSONC
        exclude: .vscode/settings.json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        entry: |
          bash -c "
            python -m pip install --upgrade pip setuptools wheel \
            && poetry install --no-ansi \
            && exec poetry run mypy $@
          "
        args: ["--install-types"]
